post http://localhost:5000/mora-backend/us-central1/api/login
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImRjMGMzNWZlYjBjODIzYjQyNzdkZDBhYjIwNDQzMDY5ZGYzMGZkZWEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vbW9yYS1iYWNrZW5kIiwiYXVkIjoibW9yYS1iYWNrZW5kIiwiYXV0aF90aW1lIjoxNTg2NTczMDIyLCJ1c2VyX2lkIjoiWFRTQ1VHT3VHNWZpeWRIU0UyM0swWVh4VTJNMiIsInN1YiI6IlhUU0NVR091RzVmaXlkSFNFMjNLMFlYeFUyTTIiLCJpYXQiOjE1ODY1NzMwMjIsImV4cCI6MTU4NjU3NjYyMiwiZW1haWwiOiJ0ZXN0LTJAdGVzdC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsidGVzdC0yQHRlc3QuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.mkPf1JE6nX8TqLKTj9ltDW2woVD-7Dz6fOkLFXrEok0TXYHbHlpzLz-YAwQMFqaoGjxYxMM9E9Xp88MiNgQ4sIZFDl-wzME6tLsr6Ws5lbsXg10nkzIIcd4kAtgj3kUMCS1VA1mUuLTX6dst7mnBjxqCOSd1AMYixCYxZ4nDTYVB74H8rHB2E3oyfqZWlpX2ChLZKVnh6pMWe-w_EWlqdOjIwPGk3Gkksjbt_MTzdjM9D5prNhfZSAMTrEK0qiY14QS0Fhb6Zz576W-tAeQpYuIo2WhcJOqIKU2Z_-t9gtQtr-skZwDRm8wT1lfhDMQNgsW9bJXOny01OmL1cPYnGA

{
    "email":"test-2@test.com",
    "password":"test@123"
}

###

post http://localhost:5000/mora-backend/us-central1/api/register
Content-Type: application/json

{
    "email":"test-2@test.com",
    "password":"test@123"
}